<div class="report-row <?php echo abs($params['val1'] - $params['val2']) > 0.01 ? 'error' : 'ok' ?>">
    <?php echo $params['name1']; ?> <span class="report-row-val"><?php echo F::formatMoneyPenny($params['val1']); ?></span>
    <?php echo abs($params['val1'] - $params['val2']) > 0.01 ? 'НЕ' : '' ?> соответствует
    <?php echo $params['name2']; ?> <span class="report-row-val"><?php echo F::formatMoneyPenny($params['val2']); ?></span>
</div>
