<div class="dialogTitle">Добро пожаловать!</div>
<div class="dialogMessageBox">
    <div class="dialogMessageBorder"></div>
    <div class="dialogMessage">
        <b>Пожалуйста, введите ваш логин и пароль.</b><br/>
        Или нажмите на ссылку, чтобы <a href="#dialog" name="modal" url="/auth/register">Зарегистрироваться</a>.
    </div>
</div>
<form id="form" action="/auth/login2">
<div class="input-label">Ваш Email</div>
<div class="input-field">
    <label for="email">Введите Email</label>
    <input type="text" name="email" id="email" value="" class="fieldCheck"
        params='<?php echo json_encode(array(array('form', 'EmailAddress'))); ?>' />
</div>
<div class="clear"></div>
<div class="input-label">Ваш пароль</div>
<div class="input-field">
    <label for="password">Введите пароль</label>
    <input type="password" name="password" id="password" value="" />
</div>
<div class="clear"></div>
<?php echo ControllerBase::getCsrfProtection(); ?>
<div class="input-button">
<button>
    <span class="button-text">Войти</span>
    <span class="button-wait"><img src="/img/css/upload_inv_mono.gif"></span>
</button>
</div>
</form>

<script>
ML.dialogLoaded($("#form"));
</script>
