<div class="dialogTitle">Моментальная регистрация</div>
<div class="dialogMessageBox">
    <div class="dialogMessageBorder"></div>
    <div class="dialogMessage">
        <b>Пожалуйста, укажите Ваше имя и фамилию.</b><br/>
        В целях корректной обработки платежей, используйте настоящие имя и фамилию.
    </div>
</div>
<form id="reg-form" action="/auth/register2">
<div class="input-label">Ваше имя</div>
<div class="input-field">
    <label for="first_name">Введите имя</label>
    <input type="text" name="first_name" id="first_name" value="" class="fieldCheck"
        params="<?php echo htmlspecialchars(json_encode(array(
            array('local', 'regExp', AuthController::RESTRICT_NAME_REGEXP),
            array('local', 'stringLength', 1, AuthController::RESTRICT_NAME_MAX_LENGTH),
        ))); ?>">
</div>
<div class="clear"></div>
<div class="input-label">Ваша фамилия</div>
<div class="input-field">
    <label for="last_name">Введите фамилию</label>
    <input type="text" name="last_name" id="last_name" value="" class="fieldCheck"
        params="<?php echo htmlspecialchars(json_encode(array(
            array('local', 'regExp', AuthController::RESTRICT_NAME_REGEXP),
            array('local', 'stringLength', 1, AuthController::RESTRICT_NAME_MAX_LENGTH),
        ))); ?>">
</div>
<div class="clear"></div>
<div class="input-button">
<button>
    <span class="button-text">Зарегистрироваться</span>
    <span class="button-wait"><img src="/img/css/upload_inv_mono.gif"></span>
</button>
</div>
</form>

<script>
FieldCheck.initAll();
$("#reg-form").submit(function( event ) {
    event.preventDefault();
    var form = $( this );
    form.find('.button-text').hide();
    form.find('.button-wait').show();
    $.post(form.attr( "action" ), form.serialize(),
        function(data) {
            if (data.status == 'error') {
                form.find('.button-wait').hide();
                form.find('.button-text').show();
                $(".dialogMessage").html(data.message);
                $(".dialogMessageBorder").css("width", $(".dialogMessage").css("width")).css("height", $(".dialogMessage").css("height"));
                $(".dialogMessageBorder").fadeTo(0, 1).fadeTo(600, 0);
            }
            if (data.status == 'ok') {
            	$(".dialogMessage").html(data.message);
            	form.attr("action", data.action);
            	form.html(data.content);
            	FieldCheck.initAll();
            }
            if (data.status == 'redirect') {
                document.location = data.url;
            }
        }, "json");
});
</script>