<div class="input-label">Ваш Email</div>
<div class="input-field">
    <label for="email">Введите Email</label>
    <input type="text" name="email" id="email" value="" class="fieldCheck"
        params='<?php echo json_encode(array(array('form', 'EmailAddress'), array('form', 'EmailNotExists'))); ?>' />
</div>
<div class="clear"></div>
<?php echo ControllerBase::getCsrfProtection(); ?>
<div class="input-button">
<button>
    <span>Продолжить</span>
</button>
</div>
