<div class="dialogTitle">Моментальная регистрация</div>
<div class="dialogMessageBox">
    <div class="dialogMessageBorder"></div>
    <div class="dialogMessage">
        <b>Пожалуйста, укажите Ваше имя и фамилию.</b><br/>
        В целях корректной обработки платежей, используйте настоящие имя и фамилию.
    </div>
</div>
<form id="reg-form" action="/auth/register2">
<div class="input-label">Ваше имя</div>
<div class="input-field">
    <label for="firstname">Введите имя</label>
    <input type="text" name="firstname" id="firstname" value="" class="fieldCheck">
</div>
<div class="clear"></div>
<div class="input-label">Ваша фамилия</div>
<div class="input-field">
    <label for="lastname">Введите фамилию</label>
    <input type="text" name="lastname" id="lastname" value="" class="fieldCheck">
</div>
<div class="clear"></div>
<div class="input-button">
<button>
    <span>Зарегистрироваться</span>
</button>
</div>
</form>

<script>
FieldCheck.initAll();
$("#reg-form").submit(function( event ) {
    event.preventDefault();
    var form = $( this );
    $.post(form.attr( "action" ), form.serialize(),
        function(data) {
            if (data.status == 'error') {
                $(".dialogMessage").html(data.message);
                $(".dialogMessageBorder").css("width", $(".dialogMessage").css("width")).css("height", $(".dialogMessage").css("height"));
                $(".dialogMessageBorder").fadeTo(0, 1).fadeTo(600, 0);
            }
            if (data.status == 'ok') {
            	$(".dialogMessage").html(data.message);
            	form.attr("action", data.action);
            	form.html(data.content);
            	FieldCheck.initAll();
            }
        }, "json");
});
</script>