<div class="customer-orders-container">
    <div class="customer-order-title">Ваши заказы</div>
    В работе <span class="customer-order-count"><?php echo $params['ordersInWork']; ?></span>
    Завершенных <span class="customer-order-count"><?php echo $params['ordersExecuted']; ?></span>
    <div class="balance-links">
        <a href="#dialog" name="modal" url="/customer/neworder">Разместить заказ</a>
    </div>
</div>
