</div>

<hr />
<div class="bottom-links">
    <a href="/index/bookkeeping">Бухгалтерская сводка</a>
    <a href="#dialog" name="modal" url="/auth/regexecutor">Регистрация исполнителя</a>
</div>
<div class="bottom">
УСВАЗ (C) Олег Белокопытов, 2014. Время генерации: <b><?php echo F::getScriptTime(); ?></b>.<br/>
</div>

<?php echo Debuger::output(); ?>
</div>
<div class="left-panel">
    <div class="left-panel-link-container">
        <a class="link-up">Наверх</a>
    </div>
</div>
</body>
</html>
