<div class="indexpage-title">Кабинет заказчика</div>
<?php $controller->renderView($params, '/customer/partial/balance');  ?>
<div class="customer-step2">
    <img src="/img/step2.jpg">
</div>
<div class="customer-right-panel">
    <?php $controller->renderView($params, '/customer/partial/orders');  ?>
    <div class="customer-step3">
        <img src="/img/step3.jpg">
    </div>
</div>
<div class="clear"></div>