<div class="indexpage-title">Спасибо, Ваш заказ размещён успешно!</div>
<?php $controller->renderView($params, '/customer/partial/balance');  ?>
<div class="customer-step4">
    <img src="/img/step4.jpg">
</div>
<div class="customer-right-panel">
    <?php $controller->renderView($params, '/customer/partial/orders');  ?>
    <div class="customer-register-executor">
        Для регистрации исполнителем нажмите снизу ссылку "Регистрация исполнителя".
    </div>
</div>
<div class="clear"></div>
