<div class="indexpage-title">Спасибо, Ваш заказ размещён успешно!</div>
<div class="background-step4">
    <?php $controller->renderView($params, '/customer/partial/balance');  ?>
    <div class="customer-right-panel">
        <?php $controller->renderView($params, '/customer/partial/orders');  ?>
        <div class="customer-register-executor">
            Для регистрации исполнителем нажмите<br/>на ссылку <a href="#dialog" name="modal" url="/auth/regexecutor">Регистрация исполнителя</a>.
        </div>
    </div>
</div>
<div class="clear"></div>
